# Generated by Django 2.1.4 on 2018-12-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='12345678910', max_length=20),
            preserve_default=False,
        ),
    ]
