# Generated by Django 2.1.4 on 2018-12-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20181221_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='timestamp',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
