# Generated by Django 2.1.4 on 2018-12-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_email',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified_phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
