# Generated by Django 2.1.4 on 2018-12-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181227_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
