# Generated by Django 2.1.4 on 2018-12-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20181227_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='budget_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.Budget'),
        ),
    ]
