# Generated by Django 2.1.4 on 2018-12-27 02:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0003_budgets_short_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budgets',
            new_name='Budget',
        ),
    ]
