# Generated by Django 2.1.4 on 2018-12-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_auto_20181227_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='short_name',
        ),
    ]
