# Generated by Django 2.1.4 on 2018-12-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_remove_budget_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='user_id',
            new_name='user',
        ),
    ]
